#ifndef COMMON_H
#define COMMON_H

typedef enum request_type_e {
	LOGIN_REQ,
	SIGNUP_REQ,
	CREATE_CHAT_REQ,
	CHAT_SEARCH_REQ,
	JOIN_CHAT_REQ,
	GET_CHAT_PARTICIPANTS_REQ,
	QUIT_REQ
}            request_type;

typedef enum respond_type_e {
	LOGIN_ERR_RESP,
	SIGNUP_ERR_RESP,
	SIGNUP_SUCCESS_RESP,
	LOGIN_SUCESS_RESP,
	CHAT_CREATION_SUCCESS_RESP,
	CHAT_CREATION_ERR_RESP,
	ADD_CHAT_MEM_ERR_RESP,
	ADD_CHAT_MEM_SUCCESS_RESP,
	CHAT_SEARCH_RESP,
	PARTICIPANTS_RESP
}			  respond_type;


#endif